global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - authentication-service-mr3y.onrender.com

  - job_name: 'shipment-service'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - shipment-service-sena.onrender.com

  - job_name: 'tracking-service'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - tracking-hq1g.onrender.com

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus' 
    scheme: https
    static_configs:
      - targets:
          - gateway-service-hql9.onrender.com