apiVersion: v1
kind: ConfigMap
metadata:
  name: paquetrack-config
  namespace: paquetrack

data:
  APIDOCS_PATH: "/v3/api-docs"
  FORWARD_HEADERS_STRATEGY: "FRAMEWORK"
  HIBERNATE_TIME_ZONE: "UTC"
  JPA_HBM2DDL_AUTO: "validate"
  JPA_OPEN_IN_VIEW: "false"
  JPA_SHOW_SQL: "false"
  JWT_ACCESS_TOKEN_TTL_SECONDS: "3600"
  JWT_REFRESH_TOKEN_TTL_SECONDS: "604800"
  LOGIN_RATE_LIMIT: "5"
  MVC_PROBLEMDTLS_ENABLED: "true"
  PORT: "8080"
  SECURITY_HSTS_ENABLED: "true"
  SPRING_PROFILES_ACTIVE: "prod"
  SWAGGER_UI_PATH: "/swagger-ui.html"
  WEB_ERROR_INCLUDE_STACKTRACE: "never"

  SPRING_RABBITMQ_PORT: "5671"
  SPRING_RABBITMQ_SSL_ENABLED: "true"
  SPRING_RABBITMQ_HOST: "shrimp.rmq.cloudamqp.com"
  SPRING_RABBITMQ_VHOST: "edjhxutz"

  PROD_AUTH_SERVICE_URL: "http://authentication-service:8080"
  PROD_SHIPMENT_SERVICE_URL: "http://shipment-service:8080"
  PROD_TRACKING_SERVICE_URL: "http://tracking-service:8080"
  PROD_UI_ORIGIN: "http://ui-service:80"