apiVersion: v1
kind: Secret
metadata:
  name: paquetrack-secrets
  namespace: paquetrack
type: Opaque
stringData:
  # Authentication Service
  AUTH_DB_URL: "jdbc:postgresql://YOUR_HOST/YOUR_DB"
  AUTH_DB_USER: "USERNAME"
  AUTH_DB_PASSWORD: "PASSWORD"

  # Shipment Service
  SHIPMENT_DB_URL: "jdbc:postgresql://YOUR_HOST/YOUR_DB"
  SHIPMENT_DB_USER: "USERNAME"
  SHIPMENT_DB_PASSWORD: "PASSWORD"

  # Tracking Service
  TRACKING_DB_URL: "jdbc:postgresql://YOUR_HOST/YOUR_DB"
  TRACKING_DB_USER: "USERNAME"
  TRACKING_DB_PASSWORD: "PASSWORD"

  # RabbitMQ
  RABBITMQ_HOST: "HOST"
  RABBITMQ_PORT: "5671"
  RABBITMQ_USER: "USERNAME"
  RABBITMQ_PASSWORD: "PASSWORD"
  RABBITMQ_VHOST: "VHOST"

  # JWT
  JWT_SECRET: "JWT_SECRET"
